const colors = {
  light: {
    text: "#080e1a",
    tint: "#0ECB81",
    background: "#f0f4ff",
    foreground: "#080e1a",
    card: "#ffffff",
    cardForeground: "#080e1a",
    primary: "#0ECB81",
    primaryForeground: "#ffffff",
    secondary: "#e8edf8",
    secondaryForeground: "#080e1a",
    muted: "#e5e8ef",
    mutedForeground: "#6b7a9e",
    accent: "#e0f8f0",
    accentForeground: "#0ECB81",
    destructive: "#F6465D",
    destructiveForeground: "#ffffff",
    border: "#dde3f0",
    input: "#dde3f0",
    success: "#0ECB81",
    warning: "#f59e0b",
  },
  dark: {
    text: "#EAECEF",
    tint: "#0ECB81",
    background: "#0B0E11",
    foreground: "#EAECEF",
    card: "#1C2127",
    cardForeground: "#EAECEF",
    primary: "#0ECB81",
    primaryForeground: "#000000",
    secondary: "#2B3139",
    secondaryForeground: "#EAECEF",
    muted: "#1E2329",
    mutedForeground: "#848E9C",
    accent: "#0C3325",
    accentForeground: "#0ECB81",
    destructive: "#F6465D",
    destructiveForeground: "#ffffff",
    border: "#2B3139",
    input: "#2B3139",
    success: "#0ECB81",
    warning: "#F0B90B",
  },
  radius: 8,
};

export default colors;
